exports.config_dev={
	//postgresql
	//host
	host:"geoanddev.c5jef5ldufvl.us-east-1.rds.amazonaws.com",
	port:5432,
	database:"geoand",
	user:"fearlessgeoand",
	password:"a5ffkXIVujQEdYD"
}

exports.config={
	//postgresql
	//host
	host:"geoanddev.c5jef5ldufvl.us-east-1.rds.amazonaws.com",
	port:5432,
	database:"geoand",
	user:"fearlessgeoand",
	password:"a5ffkXIVujQEdYD"
}